#! /bin/bash

#This is the setup script for my .vimrc and .bashrc

echo "creating backups..."
cp ~/.bashrc bashrc.bak
cp ~/.vimrc vimrc.bak

echo "removing ~/.bashrc..."
rm ~/.bashrc
cp .bashrc ~/.bashrc

echo "removing ~/.vimrc..."
rm ~/.vimrc
cp .vimrc ~/.vimrc

echo "adding jellybeans..."
cp .vim/colors/jellybeans.vim ~/.vim/colors/

echo "installing archey..."
sudo cp archey /usr/bin/

echo "config complete"

